package FileSharing;


/**
* FileSharing/FileSharingServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filesharing.idl
* Monday, March 24, 2025 5:56:33 o'clock PM PDT
*/

public interface FileSharingServiceOperations 
{
  void registerFile (String fileName, int userId);
  void removeFile (String fileName, int userId);
  String[] searchFile (String fileName);
  String getFileOwner (String fileName);
  String getFileInfo (int fileId);
  String downloadFile (String fileName);
} // interface FileSharingServiceOperations
