package FileSharing;


/**
* FileSharing/FileSharingServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filesharing.idl
* Monday, March 24, 2025 5:56:33 o'clock PM PDT
*/

abstract public class FileSharingServiceHelper
{
  private static String  _id = "IDL:FileSharing/FileSharingService:1.0";

  public static void insert (org.omg.CORBA.Any a, FileSharing.FileSharingService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FileSharing.FileSharingService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FileSharing.FileSharingServiceHelper.id (), "FileSharingService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FileSharing.FileSharingService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileSharingServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FileSharing.FileSharingService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FileSharing.FileSharingService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSharing.FileSharingService)
      return (FileSharing.FileSharingService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FileSharing._FileSharingServiceStub stub = new FileSharing._FileSharingServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FileSharing.FileSharingService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSharing.FileSharingService)
      return (FileSharing.FileSharingService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FileSharing._FileSharingServiceStub stub = new FileSharing._FileSharingServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
