package FileSharing;


/**
* FileSharing/FileSharingService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filesharing.idl
* Monday, March 24, 2025 5:56:33 o'clock PM PDT
*/

public interface FileSharingService extends FileSharingServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSharingService
