package FileSharing;


/**
* FileSharing/StringListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filesharing.idl
* Monday, March 24, 2025 5:57:12 o'clock PM PDT
*/

public final class StringListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringListHolder ()
  {
  }

  public StringListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSharing.StringListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSharing.StringListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSharing.StringListHelper.type ();
  }

}
